name: Super-Linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8.7.0
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Hanya jalankan pengecekan penting saja
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
          VALIDATE_GITHUB_ACTIONS: true
          # Matikan semua yang lain
          VALIDATE_CHECKOV: false
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_GITLEAKS: false
          VALIDATE_GIT_MERGE_CONFLICT_MARKERS: false
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_PRE_COMMIT: false
          VALIDATE_SPELL_CODESPELL: false
          VALIDATE_TRIVY: false
          VALIDATE_YAML_PRETTIER: false
          # Abaikan folder content agar tidak dicek
          FILTER_REGEX_EXCLUDE: .*content/.*
