name: Super-Linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8.7.0
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Hanya aktifkan linter ini (sisanya otomatis nonaktif)
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
          VALIDATE_GITHUB_ACTIONS: true
          # Abaikan folder content
          FILTER_REGEX_EXCLUDE: .*content/.*
